"""Fetch Natural Earth coastlines, simplify them, and emit a compact JSON.

Run once, by hand. The output is committed; the page never fetches it.

    python tools/build_coastline.py

Natural Earth is public domain (https://www.naturalearthdata.com/about/terms-of-use/).
The 110 m scale is the coarsest they publish, which is the right one here: the
globe is a few hundred pixels across, so anything finer would be discarded by
the rasteriser anyway and would only cost download size.

Simplification is Douglas-Peucker with a tolerance in degrees. Coordinates are
rounded to two decimals — about 1 km at the equator, well below one pixel at
any zoom this globe offers.
"""

import json
import math
import urllib.request
from pathlib import Path

SOURCE = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/"
    "geojson/ne_110m_coastline.geojson"
)
OUT = Path(__file__).parent.parent / "src" / "coastline.js"

TOLERANCE = 0.35  # degrees
PRECISION = 2


def perpendicular_distance(point, start, end):
    (x, y), (x1, y1), (x2, y2) = point, start, end
    dx, dy = x2 - x1, y2 - y1
    if dx == 0 and dy == 0:
        return math.hypot(x - x1, y - y1)
    t = max(0, min(1, ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)))
    return math.hypot(x - (x1 + t * dx), y - (y1 + t * dy))


def douglas_peucker(points, tolerance):
    if len(points) < 3:
        return points

    worst = 0.0
    index = 0
    for i in range(1, len(points) - 1):
        distance = perpendicular_distance(points[i], points[0], points[-1])
        if distance > worst:
            worst, index = distance, i

    if worst <= tolerance:
        return [points[0], points[-1]]

    left = douglas_peucker(points[: index + 1], tolerance)
    right = douglas_peucker(points[index:], tolerance)
    return left[:-1] + right


def flatten(geometry):
    kind = geometry["type"]
    coordinates = geometry["coordinates"]
    if kind == "LineString":
        return [coordinates]
    if kind == "MultiLineString":
        return coordinates
    if kind == "Polygon":
        return coordinates
    if kind == "MultiPolygon":
        return [ring for polygon in coordinates for ring in polygon]
    return []


def main():
    request = urllib.request.Request(SOURCE, headers={"User-Agent": "wetbulb-build/1.0"})
    with urllib.request.urlopen(request, timeout=120) as response:
        data = json.load(response)

    lines = []
    before = 0
    for feature in data["features"]:
        for line in flatten(feature["geometry"]):
            points = [(float(x), float(y)) for x, y in line]
            before += len(points)
            simplified = douglas_peucker(points, TOLERANCE)
            if len(simplified) < 2:
                continue
            lines.append(
                [[round(x, PRECISION), round(y, PRECISION)] for x, y in simplified]
            )

    after = sum(len(line) for line in lines)
    body = json.dumps(lines, separators=(",", ":"))

    OUT.write_text(
        "/**\n"
        " * World coastlines, simplified.\n"
        " *\n"
        " * Source: Natural Earth 110 m coastline, public domain.\n"
        " * https://www.naturalearthdata.com/about/terms-of-use/\n"
        " *\n"
        " * Generated by tools/build_coastline.py — do not edit by hand.\n"
        f" * Douglas-Peucker at {TOLERANCE}°, coordinates to {PRECISION} decimals:\n"
        f" * {before} points reduced to {after}.\n"
        " *\n"
        " * Committed rather than fetched: the page must keep working offline,\n"
        " * and a coastline does not change often enough to justify a request.\n"
        " */\n\n"
        "/** Each entry is a polyline of [longitude, latitude] pairs. */\n"
        f"export const COASTLINE = {body};\n",
        encoding="utf-8",
    )

    print(f"{OUT.name}: {len(lines)} lines, {before} -> {after} points, {len(body) // 1024} KB")


if __name__ == "__main__":
    main()
