"""Write src/climatology.js from whatever the cache currently holds.

Split out of build_climatology.py so a long run can be inspected while it is
still going, and so a rebuild does not have to refetch anything.

    python tools/emit_climatology.py
"""

import json
from pathlib import Path

HERE = Path(__file__).parent
CACHE = HERE / ".climatology-cache.json"
OUT = HERE.parent / "src" / "climatology.js"

STEP = 6.0
YEARS = [2022, 2023, 2024]
PERCENTILE = 95


def main():
    if not CACHE.exists():
        raise SystemExit("no cache yet — run build_climatology.py first")

    cache = json.loads(CACHE.read_text(encoding="utf-8"))
    cells = [
        [float(key.split(",")[0]), float(key.split(",")[1]), value]
        for key, value in sorted(cache.items())
        if value is not None
    ]
    cells.sort(key=lambda cell: (cell[0], cell[1]))

    body = json.dumps(cells, separators=(",", ":"))
    meta = {
        "years": YEARS,
        "step": STEP,
        "percentile": PERCENTILE,
        "cells": len(cells),
    }

    OUT.write_text(
        "/**\n"
        " * Where wet-bulb temperature is structurally dangerous.\n"
        " *\n"
        f" * Each cell: [latitude, longitude, {PERCENTILE}th percentile wet bulb in °C].\n"
        " *\n"
        " * Computed once from ERA5 reanalysis via Open-Meteo's archive API over\n"
        f" * {YEARS[0]}–{YEARS[-1]}, hot season only (May–Aug north of 15°S, Nov–Feb\n"
        f" * south of it), on a {STEP}° land grid. Wet bulb by Stull (2011).\n"
        " *\n"
        f" * The {PERCENTILE}th percentile, not the maximum: a single freak hour is\n"
        " * weather, and this map is about where the heat is structural. Not the\n"
        " * mean either, which would wash out the extremes that matter.\n"
        " *\n"
        " * Shipped rather than fetched, deliberately. A bulk request counts per\n"
        " * coordinate — measured: one 600-point request exhausted the entire\n"
        " * per-minute allowance and the next five-point request returned 429. A\n"
        " * live grid would serve about sixteen page views a day. Computing this\n"
        " * once leaves the live budget for the one place a visitor asks about.\n"
        " *\n"
        " * Generated by tools/build_climatology.py — do not edit by hand.\n"
        " */\n\n"
        f"export const CLIMATOLOGY = {body};\n\n"
        f"export const CLIMATOLOGY_META = {json.dumps(meta)};\n",
        encoding="utf-8",
    )

    values = [cell[2] for cell in cells]
    print(f"{OUT.name}: {len(cells)} Zellen, {len(body) // 1024} KB")
    if values:
        print(f"  Tw: min {min(values):.1f}, max {max(values):.1f}")
        for threshold in (26, 28, 29, 31):
            count = sum(1 for value in values if value >= threshold)
            print(f"  >= {threshold} °C: {count} ({100 * count / len(values):.0f} %)")


if __name__ == "__main__":
    main()
